#!/usr/bin/env python3
"""Writes app/ui/i18n_table.inc from strings.py and checks the translations keep the printf conversions."""
import os
import re
import sys

here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, here)
from strings import S  # noqa: E402

conv = re.compile(r'%[-+ #0]*\d*(?:\.\d+)?(?:zu|lld|ld|[dsfuxc%])')


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'


seen, bad, rows = set(), 0, []
for row in S:
    en, *tr = row
    if en in seen:
        continue
    seen.add(en)
    want = conv.findall(en)
    for t in tr:
        if conv.findall(t) != want:
            print(f"conversion mismatch: {en!r} -> {t!r}", file=sys.stderr)
            bad += 1
    rows.append('    {' + ', '.join(c_str(x) for x in [en] + tr) + '},')

out = os.path.join(here, '..', 'i18n_table.inc')
with open(out, 'w', encoding='utf-8') as f:
    f.write('// Generated by app/ui/i18n/gen.py from strings.py — edit those, not this file.\n')
    f.write('static const Entry kTable[] = {\n' + '\n'.join(rows) + '\n};\n')
print(f"{len(rows)} strings → {os.path.relpath(out)}")
sys.exit(1 if bad else 0)
